services:
  postgres:
    image: postgres:15
    container_name: bankopsapi_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: bankopsapi
    ports:
      - "5433:5432"
    volumes:
      - bankopsapi_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: bankopsapi_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bank.com
      PGADMIN_DEFAULT_PASSWORD: bank123
    ports:
      - "8081:80"
    depends_on:
      - postgres

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: bankopsapi_zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: bankopsapi_kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: bankopsapi_kafka_ui
    restart: always
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

volumes:
  bankopsapi_data:
